### ISSUE TITLE
Multiple closing tags added

### ISSUE THREAD

**Issue by Bandit** [mrhanlon/less-than-slash#47] opened 2017-04-10 22:34 UTC
![2017-04-11_10h31_37](https://cloud.githubusercontent.com/assets/30508/24885360/21c419d4-1ea2-11e7-93a5-c1a62b3bf231.png)

When I type my closing tag it adds a bunch of extra tags afterwards. Any ideas?

[Link to the HTML file in question](https://gist.github.com/Bandit/086a75409760566654ea47b19d24ec5f)

This also happens with the [Tag addon](https://atom.io/packages/tag): https://github.com/uzyn/tag/issues/24

**Comment by MarcoThePoro** [comment] 2017-04-10 22:37
This is usually caused by less-than-slash being activated more than once,
try uninstall, close atom, open atom then reinstall. If the problem
persists let me know

**Comment by Bandit** [comment] 2017-04-10 22:40
That fixed it. What would cause it to be activated more than once? Multiple Atom windows open?

**Comment by MarcoThePoro** [comment] 2017-04-10 22:44
I thought I fixed it ages ago but apparently not, it usually happens when you disable and re-enable the plugin, or if you update. Something must be wrong with our deactivation handlers.

**Comment by Bandit** [comment] 2017-04-10 23:04
Interesting. I installed this addon for the first time today after uninstalling [Tag](https://atom.io/packages/tag) thinking it was faulty. Maybe it was an un-deactivated Tag instance causing the issues?

**Comment by MarcoThePoro** [comment] 2017-04-11 00:55
Just installed tag and played with the enable/disable toggle. Their package
is not deactivating properly and causing the multiple closing tags.

On Tue., 11 Apr. 2017, 9:04 am James Nisbet, <notifications@github.com>
wrote:

Interesting. I installed this addon for the first time today after
uninstalling Tag <https://atom.io/packages/tag> thinking it was faulty.
Maybe it was an un-deactivated Tag instance causing the issues?

—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/mrhanlon/less-than-slash/issues/47#issuecomment-293103716>,
or mute the thread

**Closed** 2017-04-11 01:29 UTC

**Comment by futureclint** [comment] 2018-06-26 20:05
This workaround does not seem to work for me permanently. The extra tags always come back.
